# Generated by Django 4.0.5 on 2022-06-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='productimages',
            unique_together={('product', 'id')},
        ),
    ]
