# Generated by Django 4.0.5 on 2022-06-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
