# Generated by Django 4.0.5 on 2022-06-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_productimages_image_url_alter_productimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
